workspace:
base: /go
path: src/repo/goweb-app
clone:    
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  ping:   
    image: mongo:latest
    commands:
      - sleep 3
      - mongo --host mgo --eval "{ping:1}"
      - echo "你好!"

  test:  
    image: registry.cn-hangzhou.aliyuncs.com/golang-gcc-gpp/golang:1.11.2
    group: build
    environment:
      - BRC=${DRONE_COMMIT_BRANCH}
      - SHA=${DRONE_COMMIT_SHA:0:8}
      - EVN=${DRONE_BUILD_EVENT}
      - MSG=${DRONE_COMMIT_MESSAGE}
      - TAG=${DRONE_TAG}
      - MGO=mgo:27017
    commands:
      - echo "测试成功!"
  build:
    image: registry.cn-hangzhou.aliyuncs.com/golang-gcc-gpp/golang:1.11.2
    commands:
      - echo "go build"  

services:
  mgo:
    image: mongo:latest

branches:
  include: [ master, release/* ]