version: '2'
 
services:
  drone-server:
    image: drone/drone:0.8.6
    container_name: drone-server
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /tmp/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://192.168.131.30:9000
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://192.168.131.30:3000
      - DRONE_SECRET=test
  drone-agent:
    image: drone/agent:0.8.6
    container_name: drone-agent
    command: agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
    environment:
      - DRONE_SERVER=192.168.131.30:9000
      - DRONE_SECRET=test